create extension if not exists pgcrypto;

create table if not exists public.users (
  id text primary key,
  email text not null,
  display_name text,
  profile_image text,
  anonymous boolean default false,
  message_count integer default 0,
  daily_message_count integer default 0,
  daily_reset timestamptz,
  daily_pro_message_count integer default 0,
  daily_pro_reset timestamptz,
  premium boolean default true,
  favorite_models text[] default '{}',
  system_prompt text,
  last_active_at timestamptz,
  created_at timestamptz default now()
);

create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  user_id text not null references public.users(id) on delete cascade,
  name text not null,
  created_at timestamptz default now()
);

create table if not exists public.chats (
  id uuid primary key default gen_random_uuid(),
  user_id text not null references public.users(id) on delete cascade,
  project_id uuid references public.projects(id) on delete set null,
  title text,
  model text,
  public boolean default false,
  pinned boolean default false,
  pinned_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  chat_id uuid not null references public.chats(id) on delete cascade,
  user_id text references public.users(id) on delete set null,
  role text not null check (role in ('system', 'user', 'assistant', 'data')),
  content text,
  parts jsonb,
  experimental_attachments jsonb default '[]'::jsonb,
  message_group_id text,
  model text,
  created_at timestamptz default now()
);

create table if not exists public.chat_attachments (
  id uuid primary key default gen_random_uuid(),
  chat_id uuid not null references public.chats(id) on delete cascade,
  user_id text not null references public.users(id) on delete cascade,
  file_url text not null,
  file_name text,
  file_type text,
  file_size bigint,
  created_at timestamptz default now()
);

create table if not exists public.feedback (
  id uuid primary key default gen_random_uuid(),
  user_id text not null references public.users(id) on delete cascade,
  message text not null,
  created_at timestamptz default now()
);

create table if not exists public.user_preferences (
  user_id text primary key references public.users(id) on delete cascade,
  layout text default 'fullscreen',
  prompt_suggestions boolean default true,
  show_tool_invocations boolean default true,
  show_conversation_previews boolean default true,
  multi_model_enabled boolean default false,
  hidden_models text[] default '{}',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists chats_user_updated_idx on public.chats(user_id, updated_at desc);
create index if not exists messages_chat_created_idx on public.messages(chat_id, created_at asc);
create index if not exists projects_user_created_idx on public.projects(user_id, created_at asc);
